# SA KnackpunktBRK

version: "3.9"

services:
    db:
        build: ./Database/
        restart: always
        ports:
            - "${DB_PORT}:${DB_PORT}"
        expose:
            - ${DB_PORT}
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWD}

    backend:
        build: ./Backend/
        ports:
          - "8000:${API_PORT}"
        restart: always
        depends_on:
          - db
        environment:
            API_HOST: ${API_HOST}
            DB_HOST: db
            DB_USER: ${DB_USER}
            DB_PASSWD: ${DB_PASSWD}
            DB_NAME: ${DB_NAME}
            JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
            MAIL_SERVICE_ADDRESS: ${MAIL_SERVICE_ADDRESS}
            MAIL_SERVICE_PASSWD: ${MAIL_SERVICE_PASSWD}

    frontend:
        build: ./Frontend/
        ports:
          - "${FE_PORT}:80"
        restart: always
        depends_on:
          - backend
          - db
        environment:
            FE_PORT: ${FE_PORT}

    rp:
        build: ./Reverse-Proxy/
        restart: always
        ports:
          - "80:80"
        expose:
          - "80"
        depends_on:
          - backend
          - frontend
